services:
  - type: web
    name: vleclone
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT "app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
